### ISSUE TITLE
Improve detaching entities after import

### ISSUE THREAD

**Issue by MalteWunsch** [webfactory/doctrine-orm-test-infrastructure#23]
Given two Entities:

```php
/** @ORM\Entity */
class A {
    /** @ORM\OneToMany(targetEntity="B", cascade={"persist"}) */
    private $bs;

    public function __construct()
    {
        $this->bs = new ArrayCollection();
    }

    public function addB(B $b)
    {
        $this->bs->add($b);
    }
}

/** @ORM\Entity */
class B {
    /** @ORM\ManyToOne(targetEntity="A") */
    private $a;
}
```
... and a test starting als follows:
```php
$this->infrastructure = ORMInfrastructure::createWithDependenciesFor(A::class);
$a = new A();
$a->add(new B());
$this->infrastructure->import($a);
```
... then the following:
```php
$this->infrastructure->getEntityManager()->flush();
```
causes an error: Doctrine finds a "new" entity of class A through the relation B#a.

This is because \Webfactory\Doctrine\ORMTestInfrastructure\ORMInfrastructure::import() causes only the passed entities to be detached, in this case $a. $b remains in Doctrine's identity map and the ->flush() will affect it.

I don't think of this as a problem the tester should have to look out for on their own, but I want to hide the problem in the import process. To improve the detaching, we could either

* simply call \Doctrine\ORM\EntityManager::clear(), detaching *all* entities
* or put some work in detecting associated entities with persist={"cascade"} (and "all" or whatever)

Being lazy, I'd prefer the first idea. This might rise some weird bugs as discussed in #2, but as far as I understand: only when setup and test phase are not clearly separated. And I don't think this is a scenario we need to support - @Matthimatiker ?

**Comment by Matthimatiker** [comment]
Nice catch! I agree that the tester should not have to deal with these kind of problems.

However, I am not sure about the solution. There might be situations where setup and test are not clearly separated (simulating input from a parallel request?).

It might be a good idea to completely separate the test and import entity managers (as suggested in #2). We will need to investigate if that is possible. I might find some time to have a look into that within the next days.
