### ISSUE TITLE
Symfony namespace/bunde aliases – support them?

### ISSUE THREAD

**Issue by mpdude** [webfactory/doctrine-orm-test-infrastructure#26]
In Symfony, there's a (useful?) feature that automatically creates "alias" names for Doctrine entity namespaces (https://symfony.com/doc/current/reference/configuration/doctrine.html#alias).

Personally, I have never really used this (or even missed it), but chances are people that rely on this in their repository code cannot use our `ORMInfrastructure`.

Do you think we should consider supporting it at all?

**Comment by MalteWunsch** [comment]
If anybody provides a PR I'd be happy to merge it, but I wouldn't invest my time until I know there is an actual need.

**Comment by Okhoshi** [comment]
Given the aliases are deprecated in Doctrine and set for removal in the next major version, I think there's no point to add support from now on 😅 
See https://github.com/doctrine/orm/issues/8818
